name: 'Secret Existence'
description: 'GitHub Action to check for file existence'
author: 'Samuel Villegas'
branding:
  icon: 'file-text'  
  color: 'blue'
inputs:
  files:
    description: 'Comma separated string with paths to files and directories to check for existence.'
    required: true
outputs:
  secret_exists:
    description: 'Wheter the file(s) exists or not.'
runs:
  using: 'node12'
  main: 'dist/index.js'
